--
-- Name: marketplace; Type: SCHEMA; Schema: -; Owner: tcero
--

CREATE SCHEMA IF NOT EXISTS marketplace;

ALTER SCHEMA marketplace OWNER TO tcero;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA marketplace;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;

--
-- Name: productos; Type: TABLE; Schema: marketplace; Owner: tcero
--

CREATE TABLE marketplace.productos (
    id integer,
    text text,
    author character varying(125),
    tags text,
    job_id uuid,
    processed_at timestamp without time zone
);

CREATE TABLE marketplace.users (
    user_id uuid,
    nombre text,
    password text,
    roles text,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS marketplace.modelos(
	id integer,
    id_job bigint,
	modelo varchar(125) UNIQUE,
	descripcion text,
	created_at timestamp,
	deleted_at timestamptz null,
	PRIMARY KEY(id,id_job)
);

CREATE TABLE IF NOT EXISTS marketplace.posts(
	id integer,
	id_modelos integer,
    id_job bigint,
	descripcion text,
	modelo varchar(125),
	fechaRegistro timestamp,
	created_at timestamp,
	likes integer,
	PRIMARY KEY (id,id_job)
);
CREATE TABLE IF NOT EXISTS marketplace.servicios (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE marketplace.ts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_job bigint NOT NULL,
    portal marketplace.portal_enum NOT NULL,
    idpagina TEXT NOT NULL,
    nombre TEXT,
    edad INT,
    ciudad marketplace.ciudad_enum,
    descripcion TEXT,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    scraped_at TIMESTAMP DEFAULT NOW(),

    descripcion_tsv tsvector GENERATED ALWAYS AS (
        to_tsvector('spanish', coalesce(descripcion, ''))
    ) STORED,

    UNIQUE (portal, idpagina)
);
CREATE TABLE marketplace.ts_servicios (
    ts_id UUID NOT NULL,
    servicio_id INT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('principal', 'adicional')), -- para distinguir servicios vs servicios_adicionales

    PRIMARY KEY (ts_id, servicio_id, tipo),
    FOREIGN KEY (ts_id) REFERENCES marketplace.ts(id) ON DELETE CASCADE,
    FOREIGN KEY (servicio_id) REFERENCES marketplace.servicios(id) ON DELETE RESTRICT
);

ALTER TABLE scrap.servicios_alias
ADD CONSTRAINT fk_servicios_alias_servicio
FOREIGN KEY (id_servicio)
REFERENCES marketplace.servicios(id);

CREATE INDEX idx_ts_servicios_ts_id ON marketplace.ts_servicios(ts_id);
CREATE INDEX idx_ts_servicios_servicio_id ON marketplace.ts_servicios(servicio_id);
CREATE INDEX idx_ts_servicios_tipo ON marketplace.ts_servicios(tipo);
CREATE INDEX idx_tss_servicio_ts ON marketplace.ts_servicios (servicio_id, ts_id);

CREATE INDEX idx_ts_descripcion_fts_gin 
ON marketplace.ts USING GIN (descripcion_tsv) 
WHERE deleted_at IS NULL;
CREATE INDEX idx_ts_portal 
ON marketplace.ts (portal) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_ts_id_job 
ON marketplace.ts (id_job) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_ts_ciudad 
ON marketplace.ts (ciudad) 
WHERE deleted_at IS NULL;

CREATE INDEX ON marketplace.modelos (deleted_at);
CREATE INDEX ON scrap.modelos (id_job, id);
