FROM mcr.microsoft.com/playwright/python:v1.50.0-noble AS base
ENV PWDEBUG=0
ENV PYTHONUNBUFFERED=1
RUN groupadd -r app && useradd -r -g app -m app

WORKDIR /app
COPY scrap-service/requirements.txt /app/requirements.txt

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    python3-dev \
    python3-venv

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt


COPY --chown=app:app scrap-service/ /app

USER app

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \
  CMD python -c "import sys,requests; sys.exit(0 if True else 1)" || exit 1

ENTRYPOINT [ "celery", "-A", "main", "beat", "--loglevel=debug"]
