FROM node:20.18-alpine AS build
WORKDIR /app
RUN apk add --no-cache python3 make g++ 
COPY front/package*.json ./
RUN npm install
COPY front/ .
RUN npm run build
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY front/prod/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
