services:
  bff-service:
    build:
      dockerfile: ./bff-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  cache-updater-service:
    build:
      dockerfile: ./cache-updater/Dockerfile
      context: .
  broker-email-service:
    build:
      dockerfile: Dockerfile
      context: ./broker-email-service
  db-updater-service:
    build:
      dockerfile: Dockerfile
      context: ./db-updater
  db-broker-service:
    build:
      dockerfile: Dockerfile
      context: ./db-broker-service
  ws-service:
    build:
      dockerfile: Dockerfile
      context: ./ws-service
  front:
    build:
      dockerfile: deploy/Dockerfile
      context: ./front
      target: ${PROFILE}
      args:
        VITE_HOST: "${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}"
        VITE_WS: "ws://${HOST_EXTERNAL}"
        VITE_CLIENT_ID: "${CLIENT_ID}"
        VITE_MOCK: ${VITE_MOCK}
  solana-service:
    build:
      dockerfile: ./solana-service/Dockerfile
      context: .
  scrap-service:
    build:
      dockerfile: ./scrap-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  beat-service:
    build:
      dockerfile: beat-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  recomender-service:
    build:
      dockerfile: recomender-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  mediamtx-service:
    build:
      dockerfile: ./mediamtx-service/Dockerfile
      context: .
  clickhouse:
    build:
      context: ./clickhouse/image/
      dockerfile: Dockerfile
  rabbitmq-init:
    build:
      dockerfile: Dockerfile
      context: infra/docker/config/rabbitmq/
  hydra:
    build:
      dockerfile: Dockerfile
      context: infra/docker/config/hydra/
      target: ${PROFILE}
  flyway:
    build:
      dockerfile: deploy/Dockerfile
      context: flyway/
      target: ${PROFILE}