services:
  clickhouse:
    image: clickhouse:${CLICKHOUSE_VERSION}
    volumes:
      - ${CLICKHOUSE_VOLUME}/data:/var/lib/clickhouse/
      - ${CLICKHOUSE_VOLUME}/migrations:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_ADMIN_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD_FILE=/run/secrets/clickhouse_password
      - CLICKHOUSE_INITSCRIPTS_DIR=/docker-entrypoint-initdb.d
    secrets:
      - clickhouse_password
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure
secrets:
  clickhouse_password:
    external: true