services:
  clickhouse:
    image: bitnamilegacy/clickhouse:${CLICKHOUSE_VERSION}
    volumes:
      - ${CLICKHOUSE_VOLUME}/data:/bitnami/clickhouse/data
      - ${CLICKHOUSE_VOLUME}/migrations:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_ADMIN_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_ADMIN_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_INITSCRIPTS_DIR=/docker-entrypoint-initdb.d
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure