services:
  clickhouse:
    image: tcero76/clickhouse:${CLICKHOUSE_VERSION}
    volumes:
      - ${CLICKHOUSE_VOLUME}/data:/var/lib/clickhouse/
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_ADMIN_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD_FILE=/run/secrets/clickhouse_password
      - CLICKHOUSE_INITSCRIPTS_DIR=/docker-entrypoint-initdb.d
    secrets:
      - clickhouse_password
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure
  houseplant:
    image: tcero76/houseplant:${HOUSEPLANT_VERSION}
    working_dir: /
    secrets:
      - clickhouse_password
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_PASSWORD_FILE: /run/secrets/clickhouse_password
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: default
secrets:
  clickhouse_password:
    external: true