version: '3.8'
services: 
  bd:
    image: postgres:14
    container_name: db
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
     - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - ${NETWORK_APPLICATION}