services:
    etcd1: &etcd
        image: tcero76/patroni.timescaledb:${PATRONI_TIMESCALEDB_VERSION:-17}
        networks:
        - ${NETWORK_APPLICATION:-application}
        environment:
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: tutorial
            ETCD_UNSUPPORTED_ARCH: arm64
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.hostname == swarm-worker-0
            restart_policy:
                condition: on-failure
        hostname: etcd1
        command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380

    etcd2:
        <<: *etcd
        hostname: etcd2
        command: etcd --name etcd2 --initial-advertise-peer-urls http://etcd2:2380

    etcd3:
        <<: *etcd
        hostname: etcd3
        command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2380

    haproxy:
        image: tcero76/patroni.timescaledb:${PATRONI_TIMESCALEDB_VERSION:-17}
        networks:
        - ${NETWORK_APPLICATION:-application}
        env_file: /root/.env
        hostname: haproxy
        ports:
            - "5000:5000"
            - "5001:5001"
        command: haproxy
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.hostname == swarm-worker-0
            restart_policy:
                condition: on-failure
        environment: &haproxy_env
            ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
            PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
            PATRONI_SCOPE: demo
        healthcheck:
            test: ["CMD", "wget", "-qO-", "http://localhost:7000/health"]

    patroni1:
        image: tcero76/patroni.timescaledb:${PATRONI_TIMESCALEDB_VERSION:-17}
        networks:
        - ${NETWORK_APPLICATION:-application}
        env_file: /root/.env
        hostname: patroni1
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.hostname == swarm-worker-0
            restart_policy:
                condition: on-failure
        secrets:
        - patroni_admin_password
        - patroni_superuser_password
        - patroni_restapi_password
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni1
    patroni2:
        image: tcero76/patroni.timescaledb:${PATRONI_TIMESCALEDB_VERSION:-17}
        networks:
        - ${NETWORK_APPLICATION:-application}
        env_file: /root/.env
        hostname: patroni2
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.hostname == swarm-worker-0
            restart_policy:
                condition: on-failure
        secrets:
        - patroni_admin_password
        - patroni_superuser_password
        - patroni_restapi_password
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni2
    patroni3:
        image: tcero76/patroni.timescaledb:${PATRONI_TIMESCALEDB_VERSION:-17}
        networks:
        - ${NETWORK_APPLICATION:-application}
        env_file: /root/.env
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.hostname == swarm-worker-0
            restart_policy:
                condition: on-failure
        secrets:
        - patroni_admin_password
        - patroni_superuser_password
        - patroni_restapi_password
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni3
    flyway:
        environment:
            POSTGRES_USER: ${PATRONI_SUPERUSER_USERNAME}
            POSTGRES_DB: ${PATRONI_ADMIN_DB}
            POSTGRES_HOST: ${PATRONI_ADMIN_HOST}
            POSTGRES_PASSWORD_FILE: /run/secrets/patroni_admin_password
            POSTGRES_PORT: ${POSTGRES_PORT_WRITE}
            URL_EXTERNAL: ${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}:${PORT_EXTERNAL}
        secrets:
        - patroni_admin_password
        deploy:
            mode: replicated-job
            restart_policy:
                condition: none
            placement:
                constraints:
                - node.hostname == swarm-manager
        depends_on:
            - haproxy
        networks:
        - ${NETWORK_APPLICATION:-application}
secrets:
    patroni_admin_password:
        external: true
    patroni_superuser_password:
        external: true
    patroni_restapi_password:
        external: true