services:
  db:
    image: timescale/timescaledb:${TIMESCALEDB_VERSION}
    # command: >
    #   postgres -c wal_level=logical
    #            -c max_wal_senders=10
    #            -c max_replication_slots=10
    volumes:
      - ${POSTGRES_VOLUME}/data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: ingress
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
     - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - ${TF_VAR_overlay_network:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-0
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          memory: 512M
  flyway:
    image: flyway/flyway
    restart: "no"
    profiles:
      - job
    command: -url=jdbc:postgresql://db:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -schemas=marketplace,scrap -locations=filesystem:/flyway/sql migrate
    volumes:
      - ${POSTGRES_VOLUME}/migrations:/flyway/sql
    networks:
      - ${TF_VAR_overlay_network:-application}
    depends_on:
      - db
volumes:
  postgres: