services:  
  broker:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          memory: 512M
  broker-job:
    image: tcero76/rabbitmq-init
    build:
      dockerfile: Dockerfile
      context: ../../rabbitmq/scripts/
    entrypoint: [ "sh", "/app/init_rabbitmq.sh" ]
    environment:
      HOST: broker
      PORT: 15672
      USERNAME: guest
      PASSWORD: guest
    deploy:
      mode: replicated-job
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname == swarm-manager
