services:
  cache:
    image: redis:${REDIS_VERSION}
    ports:
      - 6379:6379
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-0
      restart_policy:
        condition: on-failure