services:
  envoy:
    container_name: envoy
    profiles:
      - front
    tty: true
    stdin_open: true
    environment:
     - ENVOY_HOST=0.0.0.0
     - ENVOY_PORT=$PORT_EXTERNAL
    volumes:
      - ./infra/docker/config/envoy/envoy.dev.yaml:/tmpl/envoy.yaml
    ports:
      - $PORT_EXTERNAL:$PORT_EXTERNAL
    networks:
      - ${NETWORK_APPLICATION}