services:
  envoy:
    image: tcero76/envoy:0.0.0
    build:
      dockerfile: ./envoy/Dockerfile
      context: .
      target: dev
    container_name: envoy
    profiles:
      - front
    tty: true
    stdin_open: true
    environment:
     - ENVOY_HOST=0.0.0.0
     - ENVOY_PORT=$PORT_EXTERNAL
    volumes:
      - ./envoy/envoy.dev.yaml:/tmpl/envoy.yaml
    ports:
      - $PORT_EXTERNAL:$PORT_EXTERNAL
    networks:
      - ${NETWORK_APPLICATION}