services:
  mediamtx1:
    container_name: mediamtx1
    entrypoint: /mediamtx /etc/mediamtx/mediamtx.yml
    profiles:
      - media
    volumes:
      - ./infra/docker/config/mediamtx/mediamtx.yml:/etc/mediamtx/mediamtx.yml
      - ${MEDIAMTX_VOLUME}/data:/data
    environment:
      - NODE_ID=mediamtx1
      - MEDIAMTX_CONFIG_PATH=/etc/mediamtx/mediamtx.yml
    restart: unless-stopped
    networks:
      - ${NETWORK_APPLICATION:-application}
  mediamtx2:
    container_name: mediamtx2
    profiles:
      - media
    volumes:
      - ./infra/docker/config/mediamtx/mediamtx.yml:/etc/mediamtx/mediamtx.yml
      - ${MEDIAMTX_VOLUME}/data:/data
    environment:
      - NODE_ID=mediamtx2
      - MEDIAMTX_CONFIG_PATH=/etc/mediamtx/mediamtx.yml
    restart: unless-stopped
    networks:
      - ${NETWORK_APPLICATION:-application}
