services:
  db:
    image: timescale/timescaledb:2.20.1-pg17
    container_name: db
    profiles: ["postgres"]
    # command: >
    #   postgres -c wal_level=logical
    #            -c max_wal_senders=10
    #            -c max_replication_slots=10
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
     - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - ${NETWORK_APPLICATION}
  flyway:
    image: flyway/flyway
    restart: "no"
    profiles:
      - job
    command: -url=jdbc:postgresql://db:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -schemas=marketplace,scrap -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./database/migrations:/flyway/sql
    networks:
      - ${NETWORK_APPLICATION}
    depends_on:
      - db
volumes:
  postgres: