services:  
  broker:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: broker
    profiles:
      - broker
    tty: true
    stdin_open: true
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ${NETWORK_APPLICATION}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5
      timeout: 2s
  broker-job:
    image: rabbitmq:${RABBITMQ_VERSION}
    restart: "no"
    container_name: brokerJob
    entrypoint: [ "sh", "/app/init_rabbitmq.sh" ]
    environment:
      HOST: broker
      PORT: 15672
      USERNAME: guest
      PASSWORD: guest
      RECOMENDER_QUEUE: ${RECOMENDER_QUEUE}
      SCRAPY_QUEUE: ${SCRAPY_QUEUE}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_CHAT_CACHE_UPDATER_QUEUE: ${RABBITMQ_CHAT_CACHE_UPDATER_QUEUE}
      CMD_CHAT_MESSAGE_PERSISTENCE_QUEUE: ${CMD_CHAT_MESSAGE_PERSISTENCE_QUEUE}
      EVT_USER_REGISTERED_EMAIL_QUEUE: ${EVT_USER_REGISTERED_EMAIL_QUEUE}
      EVT_USER_REGISTERED_EXCHANGE: ${EVT_USER_REGISTERED_EXCHANGE}
    volumes:
      - ./config/rabbitmq/init_rabbitmq.sh:/app/init_rabbitmq.sh:ro
    profiles:
      - job
    networks:
      - ${NETWORK_APPLICATION}
    depends_on:
      - broker