services:
  bff-service:
    build:
      dockerfile: ./bff-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
    working_dir: /app/bff-service
    command: ["air"]
    volumes:
      - ./bff-service:/app/bff-service
      - ./config:/app/config
      - ./postgres:/app/postgres
      - ./clickhouse:/app/clickhouse
      - ./rabbitmq:/app/rabbitmq
      - ./redis:/app/redis
    profiles:
      - bff
    container_name: bff
    stdin_open: true
    tty: true
    environment:
      - DNS=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&options=-c%20search_path%3Dmarketplace
      - PORT=3000
      - PORT_EXTERNAL=${PORT_EXTERNAL}
      - HOST_EXTERNAL=${HOST_EXTERNAL}
      - RedirectURL=/bff/callback
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://hydra:4444
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_PORT=9000
      - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
      - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
      - GOOGLE_OAUTH2_REDIRECT_URI=${GOOGLE_OAUTH2_REDIRECT_URI}
      - PROFILE=${PROFILE}
      - REDIS_HOST=${REDIS_HOST}
    networks:
      - ${NETWORK_APPLICATION}
    depends_on:
      - db
      - cache
      - broker
  cache-updater-service:
    build:
      dockerfile: Dockerfile
      context: ../../cache-updater
    working_dir: /app
    profiles:
      - back
    container_name: cacheUpdater
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - BROKER=${BROKER}
      - RABBITMQ_CHAT_CACHE_UPDATER_QUEUE=${RABBITMQ_CHAT_CACHE_UPDATER_QUEUE}
    networks:
      - ${NETWORK_APPLICATION}
    volumes:
      - ../../cache-updater:/app
    depends_on:
      - cache
      - broker
  broker-email-service:
    build:
      dockerfile: Dockerfile
      context: ../../broker-email-service
    working_dir: /broker-email-service
    profiles:
      - back
    container_name: brokerEmail
    stdin_open: true
    tty: true
    environment:
      - EVT_USER_REGISTERED_EMAIL_QUEUE=${EVT_USER_REGISTERED_EMAIL_QUEUE}
      - BROKER=${BROKER}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    networks:
      - ${NETWORK_APPLICATION}
    volumes:
      - ../../broker-email-service:/broker-email-service
      - ../../rabbitmq:/rabbitmq
    depends_on:
      broker:
        condition: service_healthy
  db-updater-service:
    build:
      dockerfile: Dockerfile
      context: ../../db-updater
    working_dir: /app  
    profiles:
      - back
    container_name: dbUpdater
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&options=-c%20search_path%3Dmarketplace
      - BROKER=${BROKER}
      - CMD_CHAT_MESSAGE_PERSISTENCE_QUEUE=${CMD_CHAT_MESSAGE_PERSISTENCE_QUEUE}
    networks:
      - ${NETWORK_APPLICATION}
    volumes:
      - ../../db-updater:/app
    depends_on:
      - db
      - broker
  db-broker-service:
    build:
      dockerfile: Dockerfile
      context: ../../db-broker-service
    working_dir: /app  
    profiles:
      - back
    container_name: DbBroker
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&options=-c%20search_path%3Dmarketplace
      - EVT_USER_REGISTERED_EMAIL_QUEUE=${EVT_USER_REGISTERED_EMAIL_QUEUE}
      - EVT_USER_REGISTERED_EXCHANGE=${EVT_USER_REGISTERED_EXCHANGE}
      - BROKER=${BROKER}
    networks:
      - ${NETWORK_APPLICATION}
    volumes:
      - ../../db-broker-service:/app
      - ../../postgres:/postgres
    depends_on:
      - db
      - broker
  ws-service:
    build:
      dockerfile: Dockerfile
      context: ../../ws-service
    container_name: ws
    profiles:
      - ws
    tty: true
    stdin_open: true
    environment:
      - MIX_ENV=dev
      - CMD_CHAT_MESSAGE_DELIVERY_QUEUE=${CMD_CHAT_MESSAGE_DELIVERY_QUEUE}
      - CMD_CHAT_MESSAGE_SEND_EXCHANGE=${CMD_CHAT_MESSAGE_SEND_EXCHANGE}
      - RABBITMQ_HOST=broker
    ports:
      - 4000:4000
    volumes:
      - ../../ws-service:/ws-service
    depends_on:
      - broker
    networks:
      - ${NETWORK_APPLICATION}
  front:
    build:
      dockerfile: front/deploy/Dockerfile.prod
      context: .
      target: dev
    container_name: front
    profiles:
      - front
    working_dir: /app
    entrypoint: npm run dev
    tty: true
    stdin_open: true
    environment:
      - VITE_HOST=http://${HOST_EXTERNAL}:${PORT_EXTERNAL}
      - VITE_WS=ws://${HOST_EXTERNAL}:${PORT_EXTERNAL}
      - VITE_CLIENT_ID=${CLIENT_ID}
      - VITE_MOCK=${VITE_MOCK}
    ports:
     - 5173:5173
    volumes:
      - ./front:/app
    networks:
      - ${NETWORK_APPLICATION}
    depends_on:
      - envoy
  solana-service:
    build:
      dockerfile: Dockerfile
      context: ../../solana-service
    profiles:
      - solana
    working_dir: /app/
    restart: always
    entrypoint: [ "air"]
    container_name: solana-service
    tty: true
    stdin_open: true
    environment:
      - PROGRAMID=${PROGRAMID}
      - BROKER=${BROKER}
      - EVT_PAYMENT_COMPLETED_EXCHANGE=${EVT_PAYMENT_COMPLETED_EXCHANGE}
    volumes:
      - ../../solana-service:/app
    networks:
      - ${NETWORK_APPLICATION}
  scrap-service:
    build:
      dockerfile: ./scrap-service/deploy/Dockerfile
      context: .
      target: dev
    working_dir: /app/scrap-service/
    profiles:
      - scrap
    command: [ "celery", "-A", "main", "worker", "--loglevel=debug"]
    container_name: scrap-service
    tty: true
    stdin_open: true
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - BROKER=${BROKER}
      - PORT=8000
      - TOTAL_POSTS=${TOTAL_POSTS}
      - USERNAME_INSTA=${USERNAME_INSTA}
      - PASSWORD_INSTA=${PASSWORD_INSTA}
      - CMD_SCRAPY_START_QUEUE=${CMD_SCRAPY_START_QUEUE}
      - CMD_SCRAPY_START_EXCHANGE=${CMD_SCRAPY_START_EXCHANGE}
    volumes:
      - ./scrap-service:/app/scrap-service
      - ./rabbitmq:/app/rabbitmq
    depends_on:
      - broker
    networks:
      - ${NETWORK_APPLICATION}
  beat-service:
    build:
      dockerfile: beat-service/deploy/Dockerfile
      context: .
      target: dev
    working_dir: /app/beat-service/
    profiles:
      - scrap
    container_name: beat-service
    tty: true
    stdin_open: true
    environment:
      - BROKER=${BROKER}
      - CRON_HOUR=${CRON_HOUR}
      - CRON_MINUTE=${CRON_MINUTE}
      - CMD_RECOMMENDER_CALCULATE_QUEUE=${CMD_RECOMMENDER_CALCULATE_QUEUE}
      - CMD_RECOMMENDER_CALCULATE_EXCHANGE=${CMD_RECOMMENDER_CALCULATE_EXCHANGE}
      - CMD_SCRAPY_START_QUEUE=${CMD_SCRAPY_START_QUEUE}
      - CMD_SCRAPY_START_EXCHANGE=${CMD_SCRAPY_START_EXCHANGE}
    volumes:
      - ./beat-service:/app/beat-service
      - ./rabbitmq:/app/rabbitmq
    depends_on:
      - broker
      - scrap-service
    networks:
      - ${NETWORK_APPLICATION}
  recomender-service:
    build:
      dockerfile: recomender-service/deploy/Dockerfile
      context: .
      target: dev
    working_dir: /app/recomender-service/
    profiles:
      - scrap
    command: [ "celery", "-A", "main", "worker","--loglevel=debug" ]
    container_name: recomender-service
    tty: true
    stdin_open: true
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - BROKER=${BROKER}
      - PORT=8000
      - TOTAL_POSTS=${TOTAL_POSTS}
      - CACHE=redis://cache:6379/0
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CMD_RECOMMENDER_CALCULATE_QUEUE=${CMD_RECOMMENDER_CALCULATE_QUEUE}
      - CMD_RECOMMENDER_CALCULATE_EXCHANGE=${CMD_RECOMMENDER_CALCULATE_EXCHANGE}
      - CMD_SCRAPY_START_QUEUE=${CMD_SCRAPY_START_QUEUE}
      - CMD_SCRAPY_START_EXCHANGE=${CMD_SCRAPY_START_EXCHANGE}
    volumes:
      - ./recomender-service:/app/recomender-service
      - ./rabbitmq:/app/rabbitmq
    depends_on:
      - broker
      - db
    networks:
      - ${NETWORK_APPLICATION}
  mediamtx-service:
    build:
      dockerfile: Dockerfile
      context: ../../mediamtx-service
    container_name: mediamtx-service
    profiles:
      - media
    ports:
      - 3001:3001
    volumes:
      - ../../mediamtx-service:/app
    environment:
      - HYDRA_PUBLIC_URL=http://hydra:4444
      - TIME_SEC_WAIT_RTMP_CONECTION=60
      - PORT=3001
    networks:
      - ${NETWORK_APPLICATION}

