services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    profiles:
      - traefik
    command:
      - "--api.dashboard=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.rtmp.address=:1935"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=admin@sugarfever.ddns.net"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/docker/config/traefik/acme.json:/letsencrypt/acme.json
    networks:
      - ${NETWORK_APPLICATION:-application}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`sugarfever-traefik.ddns.net`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.service=api@internal