import type { Metadata } from "next";
import '@/app/globals.css';
import { Providers } from "./providers";
import Header from "@/layout/Header/Header";
import Footer from "@/layout/Footer";
import GoogleOneTap from "./GoogleOneTap";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full">
      <body className="h-full flex flex-col min-h-screen antialiased overflow-hidden">
        <Providers>
          <div className="flex min-h-screen flex-col">
            <Header/>
            <main className="flex-1 bg-white overflow-auto">
            {children}
            </main>
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
