# STAGE 1 - Build
FROM python:3.9-slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/beat-service

RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY beat-service/requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt


FROM python:3.9-slim

COPY --from=builder /venv /venv
ENV PATH="/venv/bin:$PATH"

RUN useradd -m -r app
WORKDIR /app/beat-service

COPY --chown=app:app beat-service/ .
COPY --chown=app:app rabbitmq/ .

USER app
ENV PYTHONPATH="/app"

COPY beat-service/prod/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

