FROM golang:1.25 AS builder

WORKDIR /app/bff-service
COPY ./bff-service/go.mod ./bff-service/go.sum ./
COPY ./bff-service ./ 
COPY ./postgres ../postgres
COPY ./clickhouse ../clickhouse
COPY ./redis ../redis
COPY ./rabbitmq ../rabbitmq
COPY ./config ../config
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

FROM alpine:3.20
RUN adduser -D appuser
WORKDIR /app
COPY --from=builder /app/bff-service .
USER appuser
EXPOSE 3000
USER root
RUN mv /app/prod/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
USER appuser
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
