#!/bin/sh
set -x

GOOGLE_OAUTH2_CLIENT_SECRET=$(cat "$GOOGLE_OAUTH2_CLIENT_SECRET_FILE")
export GOOGLE_OAUTH2_CLIENT_SECRET

CLIENT_SECRET=$(cat "$CLIENT_SECRET_FILE")
export CLIENT_SECRET

POSTGRES_PASSWORD=$(cat "$POSTGRES_PASSWORD_FILE")
export POSTGRES_PASSWORD
export DNS="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable&options=-c%20search_path%3Dhydra"

exec "$@"
