name: Deploy Infrastructure & Services

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
env:
  PROFILE: prod
  # Application
  PORT_EXTERNAL: 8080
  HOST_EXTERNAL: localhost
  HOST_URL: http://${HOST_EXTERNAL}:${PORT_EXTERNAL}
  HOST_WS: ws://${HOST_EXTERNAL}:${PORT_EXTERNAL}
  NETWORK_APPLICATION: application
  TF_VAR_overlay_network: application
  TAG: V0.0.0
  #secrets
  # CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD}}
  # POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
  # POSTGRES_CDC_PASSWORD: ${{ secrets.POSTGRES_CDC_PASSWORD}}
  # CLIENT_ID: ${{ secrets.CLIENT_ID}}
  # CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
  # GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH2_CLIENT_ID}}
  # GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET}}
  # SMTP_PASS: ${{ secrets.SMTP_PASS}}
  # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
  # DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN}}
  # DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET}}
  # DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY}}
  # PASSWORD_INSTA: ${{ secrets.PASSWORD_INSTA}}
  # PROGRAMID: ${{ secrets.PROGRAMID}}
  PATRONI_RESTAPI_USERNAME: admin
  PATRONI_SUPERUSER_USERNAME: postgres
  PATRONI_REPLICATION_USERNAME: replicator
  PATRONI_REPLICATION_PASSWORD: replicate
  PATRONI_admin_OPTIONS: createdb,createrole

  # Versions
  HYDRA_VERSION: v2.3.0
  OATHKEEPER_VERSION: v0.40.9
  NODE_VERSION: 24.0.1
  RABBITMQ_VERSION: 4.0-management
  MEDIAMTX_VERSION: 1.12.2
  REDIS_VERSION: 8.0.0
  ELASTICSEARCH_VERSION: 8.12.0
  KIBANA_VERSION: 8.12.0
  LOGSTASH_VERSION: 8.12.0
  CLICKHOUSE_VERSION: 25.6.4
  TIMESCALEDB_VERSION: 2.20.1-pg17
  PATRONI_TIMESCALEDB_VERSION: 17
  HOUSEPLANT_VERSION: 0.0.0
  # Volumes
  CLICKHOUSE_VOLUME: /mnt/data/clickhouse/
  POSTGRES_VOLUME: /mnt/data/timescaleDB/
  RABBITMQ_VOLUME: /mnt/data/rabbitmq/
  REDIS_VOLUME: /mnt/data/redis/
  GRAFANA_VOLUME: /mnt/data/grafana/
  PROMETHEUS_VOLUME: /mnt/data/prometheus/
  MEDIAMTX_VOLUME: /mnt/data/mediamtx/
  # jobs
  TOTAL_POSTS: 5
  CRON_HOUR: 23
  CRON_MINUTE: 12
  USERNAME_INSTA: arodnazs@hotmail.com
  #colas
  BROKER: amqp://guest:guest@broker:5672
  RECOMENDER_QUEUE: recomender_queue
  SCRAPY_QUEUE: scrapy_queue
  RABBITMQ_QUEUE: chat_event_queue
  RABBITMQ_CHAT_CACHE_UPDATER_QUEUE: chat_cache_updater_queue
  CMD_CHAT_MESSAGE_PERSISTENCE_QUEUE: cmd_chat_message_persistence_queue
  EVT_USER_REGISTERED_EMAIL_QUEUE: evt_user_registered_email_queue
  EVT_USER_REGISTERED_EXCHANGE: evt_user_registered_exchange
  # redis
  REDIS_HOST: cache
  #clickhouse
  CLICKHOUSE_USER: tcero
  # postgres
  POSTGRES_USER: tcero
  POSTGRES_DB: marketplace
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  #OAuth google
  GOOGLE_OAUTH2_REDIRECT_URI: http://localhost:8080/bff/callback
  # email
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USER: leonardo.lastra@gmail.com
  # docker
  DOCKER_USERNAME: tcero76
  MANAGER_IP: 134.209.32.181
jobs:
  terraform:
    name: Terraform Apply
    if:  false
    runs-on: ubuntu-latest
    outputs:
      manager_ip: ${{ steps.get_ip.outputs.manager_ip }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
          DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}

      - name: Get Swarm Manager IP
        id: get_ip
        run: echo "manager_ip=$(terraform -chdir=terraform output -raw manager_public_ip)" >> $GITHUB_OUTPUT

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mydockerhubuser/api
          tags: |
            type=ref,event=tag

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: vars
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Generate flattened Compose file
        run: docker compose config > docker-compose.generated.yml

      - name: Build and push images
        run: |
          docker compose -f docker-compose.generated.yml build
          docker compose -f docker-compose.generated.yml push

  swarm:
    name: Update Docker Swarm Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Crear archivo .env
        run: |
          ssh -o StrictHostKeyChecking=no root@$MANAGER_IP "bash -c 'cat > /root/.env <<EOF
          POSTGRES_USER=$POSTGRES_USER
          POSTGRES_HOST=$POSTGRES_HOST
          POSTGRES_PORT=$POSTGRES_PORT
          POSTGRES_DB=$POSTGRES_DB
          POSTGRES_VOLUME=$POSTGRES_VOLUME
          CLICKHOUSE_VOLUME=$CLICKHOUSE_VOLUME
          CLICKHOUSE_USER=$CLICKHOUSE_USER
          RABBITMQ_VERSION=$RABBITMQ_VERSION
          RABBITMQ_VOLUME=$RABBITMQ_VOLUME
          HYDRA_VERSION=$HYDRA_VERSION
          REDIS_VERSION=$REDIS_VERSION
          CLICKHOUSE_VERSION=$CLICKHOUSE_VERSION
          HOUSEPLANT_VERSION=${HOUSEPLANT_VERSION}
          HOST_EXTERNAL=$MANAGER_IP
          PORT_EXTERNAL=$PORT_EXTERNAL
          NETWORK_APPLICATION=$NETWORK_APPLICATION
          EOF'"

      - name: Crear secrets en Docker Swarm
        continue-on-error: true
        run: |
          ssh -o StrictHostKeyChecking=no root@$MANAGER_IP "
            echo '${{ secrets.POSTGRES_PASSWORD }}' | docker secret create postgres_password - \
              && echo '✅ Secret postgres_password creado' \
              || echo 'ℹ️ Secret postgres_password ya existe, continuando...'
          "
          ssh -o StrictHostKeyChecking=no root@$MANAGER_IP "
            echo '${{ secrets.CLICKHOUSE_PASSWORD }}' | docker secret create clickhouse_password - \
              && echo '✅ Secret clickhouse_password creado' \
              || echo 'ℹ️ Secret clickhouse_password ya existe, continuando...'
          "

  # PATRONI_ADMIN_PASSWORD: admin
  # PATRONI_SUPERUSER_PASSWORD: postgres
  # PATRONI_RESTAPI_PASSWORD: admin




        shell: bash

      - name: Copy docker-compose.yml to manager
        run: |
          ssh -o StrictHostKeyChecking=no root@$MANAGER_IP "
            mkdir -p docker
          "
          scp -o StrictHostKeyChecking=no infra/docker/imagenes.yml \
            root@$MANAGER_IP:/root/docker/imagenes.yml
          scp -o StrictHostKeyChecking=no infra/docker/prod/* \
            root@$MANAGER_IP:/root/docker/

      - name: Deploy stack on Swarm manager
        run: ssh -o StrictHostKeyChecking=no root@$MANAGER_IP "/root/deploy_stack.sh"




